packages:
  - apps/*
  - packages/*

catalog:
  solid-js: ^1.9.14
  '@unocss/reset': 66.2.0
  '@iconify-json/lucide': ^1.2.118
  '@unocss/preset-icons': 66.2.0
  unocss: 66.2.0
  vite: ^6.4.3
  vite-plugin-solid: ^2.11.13
  typescript: ^7.0.2
