// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StyleMeta } from "./StyleMeta";
import type { StyleVersion } from "./StyleVersion";

/**
 * **話者**(_speaker_)のメタ情報。
 */
export type SpeakerMeta = { 
/**
 * 話者名。
 */
name: string, 
/**
 * 話者に属するスタイル。
 */
styles: Array<StyleMeta>, 
/**
 * 話者のバージョン。
 */
version: StyleVersion, 
/**
 * 話者のUUID。
 */
speaker_uuid: string, 
/**
 * 話者の順番。
 *
 * `SpeakerMeta`の列は、この値に対して昇順に並んでいるべきである。
 */
order: number | null, };
