// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StyleId } from "./StyleId";
import type { StyleType } from "./StyleType";

/**
 * **スタイル**(_style_)のメタ情報。
 */
export type StyleMeta = { 
/**
 * スタイルID。
 */
id: StyleId, 
/**
 * スタイル名。
 */
name: string, 
/**
 * スタイルに対応するモデルの種類。
 */
type: StyleType, 
/**
 * スタイルの順番。
 *
 * [`SpeakerMeta::styles`]は、この値に対して昇順に並んでいるべきである。
 */
order: number | null, };
