// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **スタイル**(_style_)に対応するモデルの種類。
 */
export type StyleType = "talk" | "singing_teacher" | "frame_decode" | "sing";
