// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentPhrase } from "./AccentPhrase";

/**
 * AudioQuery (音声合成用のクエリ)。
 */
export type AudioQuery = {
  /**
   * アクセント句の配列。
   */
  accent_phrases: Array<AccentPhrase>;
  /**
   * 全体の話速。
   */
  speed_scale: number;
  /**
   * 全体の音高。
   */
  pitch_scale: number;
  /**
   * 全体の抑揚。
   */
  intonation_scale: number;
  /**
   * 全体の音量。
   */
  volume_scale: number;
  /**
   * 音声の前の無音時間。
   */
  pre_phoneme_length: number;
  /**
   * 音声の後の無音時間。
   */
  post_phoneme_length: number;
  /**
   * 音声データの出力サンプリングレート。
   */
  output_sampling_rate: number;
  /**
   * 音声データをステレオ出力するか否か。
   */
  output_stereo: boolean;
  /**
   * \[読み取り専用\] AquesTalk風記法。
   *
   * [`Synthesizer::audio_query`]が返すもののみ`Some`となる。入力としてのAudioQueryでは無視され
   * る。
   *
   * [`Synthesizer::audio_query`]: crate::blocking::Synthesizer::audio_query
   */
  kana: string | null;
};
