// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * スタイルID。
 *
 * VOICEVOXにおける、ある[**話者**(_speaker_)]のある[**スタイル**(_style_)]を指す。
 *
 * [**話者**(_speaker_)]: SpeakerMeta
 * [**スタイル**(_style_)]: StyleMeta
 */
export type StyleId = number;
